### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [BharathVishal/AndroidBatteryStats#1]
Hi, @BharathVishal. I wanted to contribute to your project and I've designed a logo for your project. if you need anything change please let me know.
![battery](https://user-images.githubusercontent.com/36124339/45371114-f96b6900-b613-11e8-9877-2289674b115d.png)
Best Regard, Mirza Zulfan

**Comment by BharathVishal** [comment]
Hi @mirzazulfan,
Thanks and feel free to add a logo under Apache 2.0 license. I'll add your name in Readme.md for logo designing.

The first logo is good. If would be good if you could remove the gradient effect in the battery icon and make it flat. Thanks.

**Comment by mirzazulfan** [comment]
Thanks for your response @BharathVishal . Im glad you liked it. Do you mean like this ?
![baterry stats](https://user-images.githubusercontent.com/36124339/45528132-83f7c800-b7ce-11e8-8258-ad4459034541.png)
I'll sent all file and create a pr. What do you think? 
Thank you. Best Regard.

**Comment by BharathVishal** [comment]
Hi mirzazulfan,
The second logo(the having the red background) would be apt if you could change the background color of it to #2ecc71(emerald green), signifying a battery's color. Thanks.

**Comment by mirzazulfan** [comment]
@BharathVishal .. Like this ?
![batery v2](https://user-images.githubusercontent.com/36124339/45528724-126d4900-b7d1-11e8-99b0-2362f68e362d.png)
Thanks.

**Comment by BharathVishal** [comment]
Exactly, it's apt. Thanks for the logo. Feel free to add the logo and create a pull request.

**Comment by mirzazulfan** [comment]
I'll upload the files and create a pr. Thank you.

**Comment by BharathVishal** [comment]
Thanks @mirzazulfan ! :) I'm closing this issue now. 👍

**Comment by mirzazulfan** [comment]
Hi @BharathVishal ,, i've created a pr #2 . Good luck with your project. 
Best Regard. :+1:
