### ISSUE TITLE
Battery will die/empty in approx time remaining

### ISSUE THREAD

**Issue by qadir-genetech** [BharathVishal/AndroidBatteryStats#3]
Hi, Congratulations for great battery stuff code.

I am searching for how to calculate the in how much estimated time my battery will be empty/die.
Android OS calculate this value too. here is screenshot of my phone.

![image](https://user-images.githubusercontent.com/14326497/67951552-91a82100-fc0d-11e9-805a-509e7e970235.png)

Is there any native way to calc this value?
It will be great feature in your app :)

**Comment by BharathVishal** [comment]
Hi, 
Thanks for your suggestion and feedback. As of now there isn't a native Android API to calculate the remaining battery time and this has to be done through our own implementation. 
Calculating the remaining battery time includes some sort of estimation based on the battery drain between timed intervals and other parameters like recent running apps, battery capacity in mAH, battery health, current battery voltage etc. I can implement an estimator in the future release.
Also, an API to calculate remaining time to charge fully is available only to devices running Android Pie(API 28) and above.
