### ISSUE TITLE
Add Feature Reamining time of battery

### ISSUE THREAD

**Issue by hafizijaz656** [BharathVishal/AndroidBatteryStats#4]
All Features are good but in this.Can you  add the remaining time of battery according to the charge

**Comment by BharathVishal** [comment]
Hi,
Thanks for your suggestion and feedback. As of now there isn't a native Android API to calculate the remaining battery time and this has to be done through our own implementation.
Calculating the remaining battery time includes some sort of estimation based on the battery drain between timed intervals and other parameters like recent running apps, battery capacity in mAH, battery health, current battery voltage etc. I can implement an estimator in the future release.
Also, an API to calculate remaining time to charge fully is available only to devices running Android Pie(API 28) and above.
